services:
  - type: web
    name: kill-counter
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free
